name: video_trimmer
description: flutter video trimmer just get time(not real trim).
version: 1.0.0
homepage: https://github.com/bluejoyq/video_trimmer

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.4.5
  video_thumbnail: ^0.5.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
